# Generated by Django 4.2.1 on 2023-12-15 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0005_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('raiting', models.SmallIntegerField(default=60, verbose_name=django.core.validators.MaxValueValidator(100))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='personal', to='Manager.project')),
            ],
        ),
    ]
