# Generated by Django 4.2.1 on 2023-12-10 18:50

import Manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('photo', models.ImageField(blank=True, default='no_avatar.jpg', null=True, upload_to=Manager.models.get_upload_path)),
                ('public_date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
