# Generated by Django 4.2.1 on 2023-12-14 23:40

import Manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_customuser_personal_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='no_avatar.jpg', null=True, upload_to=Manager.models.get_upload_path),
        ),
    ]
