# Generated by Django 4.2.1 on 2023-12-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_remove_personal_avatar_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
