# Generated by Django 4.2.1 on 2023-12-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_project_duration_project_event_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personallist',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='personal_list',
            field=models.ManyToManyField(related_name='projects', to='Manager.personallist'),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
    ]
