# Generated by Django 4.2.1 on 2023-12-21 12:39

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_remove_personallist_project_project_personal_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personallist',
            name='count',
        ),
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.CharField(choices=[('personal', 'personal on event'), ('visiting', 'organizing a visiting'), ('cleaning', 'cleaning'), ('auto', 'auto events'), ('development', 'development events'), ('security', 'event security'), ('exhibition', 'exhibition services'), ('moving', 'moving events'), ('trucking', 'trucking on events'), ('parcking', 'parking organization'), ('photography', 'event photography'), ('analisis', 'data analysis events'), ('web design', 'web design events'), ('svg Animations', 'svg animations events'), ('ui development', 'ui development events'), ('testing', 'testing events')], default=('personal', 'personal on event'), max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 21)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('public_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Manager.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
