# Generated by Django 4.2.1 on 2023-12-21 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_remove_personallist_count_alter_project_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 21, 12, 45, 29, 421142, tzinfo=datetime.timezone.utc)),
        ),
    ]
